DROP DATABASE IF EXISTS aeroport;
CREATE DATABASE aeroport DEFAULT CHARSET UTF8;
USE aeroport;


CREATE TABLE Pilotes(
   IdPilote  INT AUTO_INCREMENT PRIMARY KEY,
   Nom VARCHAR(100) NOT NULL,
   Prenom VARCHAR(100) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE Avions(
   IdAvion  INT AUTO_INCREMENT PRIMARY KEY,
   Compagnie VARCHAR(100) NOT NULL,
   Type VARCHAR(50) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE Vols(
   IdVol  INT AUTO_INCREMENT PRIMARY KEY,
   DateVol DATETIME NOT NULL,
   AeroportArrivee VARCHAR(100) NOT NULL,
   DureeVol VARCHAR(4) NOT NULL,
   AeroportDepart VARCHAR(100) NOT NULL,
   IdAvion INT NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE Affectations(
   IdAffectation INT AUTO_INCREMENT PRIMARY KEY,
   IdPilote INT,
   IdVol INT
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS utilisateurs (
idUtilisateur int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom varchar(50) NOT NULL,
prenom varchar(50) NOT NULL,
adresseMail varchar(50) UNIQUE NOT NULL,
motDePasse varchar(50) NOT NULL,
role int(11) NOT NULL COMMENT '2 Admin 1 User'
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS textes (
idTexte int (11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
codeTexte varchar (50) NOT NULL,
fr LONGTEXT NOT NULL,
en LONGTEXT NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

ALTER TABLE Vols ADD CONSTRAINT FK_Vols_Affectations FOREIGN KEY(IdAvion) REFERENCES Avions(IdAvion);
ALTER TABLE Affectations ADD CONSTRAINT FK_Affectations_Pilotes FOREIGN KEY(IdPilote) REFERENCES Pilotes(IdPilote);
ALTER TABLE Affectations ADD CONSTRAINT FK_Affectations_Vols FOREIGN KEY(IdVol) REFERENCES Vols(IdVol);   
   
